#pragma once
#include <iostream>
#include <string>
#include <fstream>
#include <memory>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <filesystem>
#include <functional>
#include <glm/glm.hpp>
#include "Tigraf/Core/Core.h"
#include "Tigraf/Core/Log.h"
#include "Tigraf/Core/Assert.h"
#include "Tigraf/Core/Timer.h"

#include "Tigraf/Core/Application.h"
#include "Tigraf/Core/Assert.h"
#include "Tigraf/Core/Core.h"
#include "Tigraf/Core/Layer.h"
#include "Tigraf/Core/Log.h"
#include "Tigraf/Core/PlatformDetection.h"
#include "Tigraf/Core/Timer.h"
#include "Tigraf/Event/Event.h"
#include "Tigraf/Input/Keycodes.h"
#include "Tigraf/Input/glfwInput.h"
#include "Tigraf/Renderer/Buffers/Buffer.h"
#include "Tigraf/Renderer/Buffers/RWBufferDefines.h"
#include "Tigraf/Renderer/Buffers/UniformBufferDefines.h"
#include "Tigraf/Renderer/Camera/Camera.h"
#include "Tigraf/Renderer/Camera/EditorCamera.h"
#include "Tigraf/Renderer/Framebuffers/Framebuffer.h"
#include "Tigraf/Renderer/GraphicsContext.h"
#include "Tigraf/Renderer/Mesh/Mesh.h"
#include "Tigraf/Renderer/Mesh/MeshPrimitives.h"
#include "Tigraf/Renderer/Renderer.h"
#include "Tigraf/Renderer/RendererAPI.h"
#include "Tigraf/Renderer/Shaders/Shader.h"
#include "Tigraf/Renderer/Textures/Texture.h"
#include "Tigraf/Window/Window.h"